services:
  backend:
    restart: always
    build:
      context: ./backend
    ports:
      - "8200:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@tv-dlog-bd:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - UPLOAD_DIR=${UPLOAD_DIR}
      - PYTHONPATH=/app/app
      - APEX_REST_URL=${APEX_REST_URL}
      - LOG_DIR=${LOG_DIR}
      - LOG_FILE=${LOG_FILE}
      - LOG_LEVEL=${LOG_LEVEL}

    networks:
      - tvdlog-network
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads # Bind-mount to keep upload files synchronized locally in the project

  frontend:
    restart: always
    build:
      context: ./frontend
    ports:
      - "3100:3100"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - DOCKER_ENV=true
    networks:
      - tvdlog-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

networks:
  tvdlog-network:
    external: true

