apiVersion: v1
kind: Secret
metadata:
  name: tvdlog-secret
  namespace: default
  labels:
    app.kubernetes.io/name: tvdlog
type: Opaque
stringData:
  POSTGRES_USER: "tvdlog"
  POSTGRES_PASSWORD: "tvdlog123"
  SECRET_KEY: "minha_chave_secreta_jwt_super_segura"
  OAUTH_CLIENT_ID: "IFfe80pwvWCMl_QLaxxxxw.."
  OAUTH_CLIENT_SECRET: "B7CEZ5X4zMXoe3LwuHGiUA.."
  DATABASE_URL: "postgresql://tvdlog:tvdlog123@tvdlog-bd-service:5432/tvdlog"
