"""initial_schema

Revision ID: 943792896ce5
Revises: 
Create Date: 2026-06-02 14:34:30.634465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943792896ce5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    # 1. Create audit_logs table if not exists
    if 'audit_logs' not in tables:
        op.create_table('audit_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('username', sa.String(length=50), nullable=True),
        sa.Column('action', sa.String(length=100), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('details', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
        )
        op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
        op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)

    # 2. Add columns to media if they don't exist
    if 'media' in tables:
        columns = [c['name'] for c in inspector.get_columns('media')]
        if 'created_at' not in columns:
            op.add_column('media', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
        if 'updated_at' not in columns:
            op.add_column('media', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
        
        # Check active index
        indexes = [idx['name'] for idx in inspector.get_indexes('media')]
        if 'ix_media_active' not in indexes:
            op.create_index(op.f('ix_media_active'), 'media', ['active'], unique=False)
        if 'ix_media_active_order' not in indexes:
            op.create_index('ix_media_active_order', 'media', ['active', 'order'], unique=False)
    else:
        # Create media table from scratch if it doesn't exist
        op.create_table('media',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('original_name', sa.String(length=255), nullable=False),
        sa.Column('type', sa.String(length=20), nullable=False),
        sa.Column('duration', sa.Integer(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('uploaded_at', sa.DateTime(), nullable=True),
        sa.Column('url', sa.String(length=500), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_media'))
        )
        op.create_index(op.f('ix_media_active'), 'media', ['active'], unique=False)
        op.create_index('ix_media_active_order', 'media', ['active', 'order'], unique=False)

    # 3. Add columns to settings if they don't exist
    if 'settings' in tables:
        columns = [c['name'] for c in inspector.get_columns('settings')]
        if 'created_at' not in columns:
            op.add_column('settings', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
        if 'updated_at' not in columns:
            op.add_column('settings', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    else:
        # Create settings table from scratch if it doesn't exist
        op.create_table('settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('key', sa.String(length=50), nullable=False),
        sa.Column('value', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
        sa.UniqueConstraint('key', name=op.f('uq_settings_key'))
        )

    # 4. Add columns to users if they don't exist
    if 'users' in tables:
        columns = [c['name'] for c in inspector.get_columns('users')]
        if 'created_at' not in columns:
            op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
        if 'updated_at' not in columns:
            op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    else:
        # Create users table from scratch if it doesn't exist
        op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('must_change_password', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
        sa.UniqueConstraint('username', name=op.f('uq_users_username'))
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('settings', 'updated_at')
    op.drop_column('settings', 'created_at')
    op.drop_index('ix_media_active_order', table_name='media')
    op.drop_index(op.f('ix_media_active'), table_name='media')
    op.drop_column('media', 'updated_at')
    op.drop_column('media', 'created_at')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
